import { v4 as uuid } from "uuid";

export default [
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_3.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_3.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
  {
    id: uuid(),
    createdAt: "27/03/2019",
    price: 250,
    sale: 0,
    name: "shoes",
    media: "/static/images/products/product_1.png",
  },
];
